name: Rust

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install
      run: cargo install --path .
    - run: cargo run
    - run: |
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-apple-darwin
        rustup target add x86_64-unknown-linux-gnu
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --target x86_64-pc-windows-gnu
        cargo build --release --target x86_64-apple-darwin
        cargo build --release --target x86_64-unknown-linux-gnu
        cargo build --release --target x86_64-unknown-linux-musl
        find target
